### ISSUE TITLE
Fix test failures (data churn)

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1148]
We have some test failures due to upstream data changes coming from OpenStreetMap.

- https://circleci.com/gh/tilezen/vector-datasource/1303

```
FAILED 6 TESTS. For more information, see 'test.log'
[   3/154] FAIL: 'integration-test/1030-invalid-wkb-polygons.py'
Traceback (most recent call last):
  File "./scripts/../integration-test.py", line 519, in run_test
    'features_in_mvt_layer': features_in_mvt_layer,
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 240, in run_path
    return _run_module_code(code, init_globals, run_name, path_name)
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "integration-test/1030-invalid-wkb-polygons.py", line 51, in <module>
    raise Exception("Ocean area %f, expected %f." % (abs(ocean_area), expected))
  File "/opt/circleci/python/2.7.10/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "./scripts/../integration-test.py", line 237, in features_in_mvt_layer
    yield features
  File "integration-test/1030-invalid-wkb-polygons.py", line 47, in <module>
    ocean_area += area_of(feature['geometry'])
  File "integration-test/1030-invalid-wkb-polygons.py", line 30, in area_of
    area += area_of_ring(outer)
  File "integration-test/1030-invalid-wkb-polygons.py", line 17, in area_of_ring
    for [px, py], [nx, ny] in zip(ring, ring[1:] + [ring[0]]):
Exception: Tile 'http://localhost:59296/water/5/17/9.mvt': cannot concatenate 'str' and 'list' objects


[  26/154] FAIL: 'integration-test/399-add-island-labels.py'
Traceback (most recent call last):
  File "./scripts/../integration-test.py", line 519, in run_test
    'features_in_mvt_layer': features_in_mvt_layer,
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 240, in run_path
    return _run_module_code(code, init_globals, run_name, path_name)
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "integration-test/399-add-island-labels.py", line 41, in <module>
    { 'kind': 'archipelago', 'label_placement': True, 'min_zoom': 15, 'name': 'Three Sisters Islands' })
  File "./scripts/../integration-test.py", line 292, in assert_has_feature
    % (properties, closest['properties'], misses)
  File "/opt/circleci/python/2.7.10/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "./scripts/../integration-test.py", line 189, in features_in_tile_layer
    yield features
  File "./scripts/../integration-test.py", line 286, in assert_has_feature
    "%r (because layer %r was empty)" % (properties, layer)
Exception: Tile 'http://localhost:59296/earth/15/9367/12534.json': Did not find feature including properties {'label_placement': True, 'kind': 'archipelago', 'min_zoom': 15, 'name': 'Three Sisters Islands'} (because layer 'earth' was empty)


[  28/154] FAIL: 'integration-test/404-toys-not-found.py'
Traceback (most recent call last):
  File "./scripts/../integration-test.py", line 519, in run_test
    'features_in_mvt_layer': features_in_mvt_layer,
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 240, in run_path
    return _run_module_code(code, init_globals, run_name, path_name)
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "integration-test/404-toys-not-found.py", line 18, in <module>
    { 'kind': 'toys' })
  File "./scripts/../integration-test.py", line 292, in assert_has_feature
    % (properties, closest['properties'], misses)
  File "/opt/circleci/python/2.7.10/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "./scripts/../integration-test.py", line 189, in features_in_tile_layer
    yield features
  File "./scripts/../integration-test.py", line 292, in assert_has_feature
    % (properties, closest['properties'], misses)
Exception: Tile 'http://localhost:59296/pois/17/38598/49259.json': Did not find feature including properties {'kind': 'toys'}. The closest match was {u'source': u'openstreetmap.org', u'kind': u'ice_cream', u'min_zoom': 17.0, u'id': 2782000317, u'name': u'Ben and Jerry'}: missed {'kind': "'ice_cream' != 'toys'"}.


[ 108/154] FAIL: 'integration-test/719-add-kind-detail-for-pois.py'
Traceback (most recent call last):
  File "./scripts/../integration-test.py", line 519, in run_test
    'features_in_mvt_layer': features_in_mvt_layer,
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 240, in run_path
    return _run_module_code(code, init_globals, run_name, path_name)
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "integration-test/719-add-kind-detail-for-pois.py", line 4, in <module>
    { 'id': 1426311638, 'kind': 'restaurant', 'kind_detail': 'seafood' })
  File "./scripts/../integration-test.py", line 292, in assert_has_feature
    % (properties, closest['properties'], misses)
  File "/opt/circleci/python/2.7.10/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "./scripts/../integration-test.py", line 189, in features_in_tile_layer
    yield features
  File "./scripts/../integration-test.py", line 286, in assert_has_feature
    "%r (because layer %r was empty)" % (properties, layer)
Exception: Tile 'http://localhost:59296/pois/16/19298/24630.json': Did not find feature including properties {'kind_detail': 'seafood', 'kind': 'restaurant', 'id': 1426311638} (because layer 'pois' was empty)


[ 111/154] FAIL: 'integration-test/742-predictable-layers-pois.py'
Traceback (most recent call last):
  File "./scripts/../integration-test.py", line 519, in run_test
    'features_in_mvt_layer': features_in_mvt_layer,
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 240, in run_path
    return _run_module_code(code, init_globals, run_name, path_name)
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "integration-test/742-predictable-layers-pois.py", line 5, in <module>
    {'id': 358830410, 'kind': 'grave_yard'})
  File "./scripts/../integration-test.py", line 292, in assert_has_feature
    % (properties, closest['properties'], misses)
  File "/opt/circleci/python/2.7.10/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "./scripts/../integration-test.py", line 189, in features_in_tile_layer
    yield features
  File "./scripts/../integration-test.py", line 286, in assert_has_feature
    "%r (because layer %r was empty)" % (properties, layer)
Exception: Tile 'http://localhost:59296/pois/17/20950/50703.json': Did not find feature including properties {'kind': 'grave_yard', 'id': 358830410} (because layer 'pois' was empty)


[ 126/154] FAIL: 'integration-test/841-normalize-boundaries-kind.py'
Traceback (most recent call last):
  File "./scripts/../integration-test.py", line 519, in run_test
    'features_in_mvt_layer': features_in_mvt_layer,
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 240, in run_path
    return _run_module_code(code, init_globals, run_name, path_name)
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "integration-test/841-normalize-boundaries-kind.py", line 21, in <module>
    {'id': 55602811, 'kind': 'aboriginal_lands', 'kind_detail': type(None)})
  File "./scripts/../integration-test.py", line 292, in assert_has_feature
    % (properties, closest['properties'], misses)
  File "/opt/circleci/python/2.7.10/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "./scripts/../integration-test.py", line 189, in features_in_tile_layer
    yield features
  File "./scripts/../integration-test.py", line 286, in assert_has_feature
    "%r (because layer %r was empty)" % (properties, layer)
Exception: Tile 'http://localhost:59296/boundaries/16/10523/22492.json': Did not find feature including properties {'kind_detail': <type 'NoneType'>, 'kind': 'aboriginal_lands', 'id': 55602811} (because layer 'boundaries' was empty)
```

**Comment by nvkelso** [comment]
Fixed with https://github.com/tilezen/vector-datasource/issues/1149.
