### ISSUE TITLE
[tests] data drift in OSM affects tests, again

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1164]
FAILED 2 TESTS. For more information, see 'test.log'

```
[ 100/154] FAIL: 'integration-test/668-intermittent-water.py'
Traceback (most recent call last):
  File "./scripts/../integration-test.py", line 519, in run_test
    'features_in_mvt_layer': features_in_mvt_layer,
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 240, in run_path
    return _run_module_code(code, init_globals, run_name, path_name)
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "integration-test/668-intermittent-water.py", line 5, in <module>
    { 'kind': 'river', 'intermittent': True })
  File "./scripts/../integration-test.py", line 292, in assert_has_feature
    % (properties, closest['properties'], misses)
  File "/opt/circleci/python/2.7.10/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "./scripts/../integration-test.py", line 189, in features_in_tile_layer
    yield features
  File "./scripts/../integration-test.py", line 292, in assert_has_feature
    % (properties, closest['properties'], misses)
Exception: Tile 'http://localhost:38708/water/16/12353/26272.json': Did not find feature including properties {'kind': 'river', 'intermittent': True}. The closest match was {u'kind': u'drain', u'name': u'Arizona Canal Diversion Channel (ACDC)', u'intermittent': True, u'sort_rank': 200, u'source': u'openstreetmap.org', u'min_zoom': 16.0, u'id': 107817218}: missed {'kind': "'drain' != 'river'"}.


[ 128/154] FAIL: 'integration-test/843-normalize-underscore.py'
Traceback (most recent call last):
  File "./scripts/../integration-test.py", line 519, in run_test
    'features_in_mvt_layer': features_in_mvt_layer,
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 240, in run_path
    return _run_module_code(code, init_globals, run_name, path_name)
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "integration-test/843-normalize-underscore.py", line 19, in <module>
    { 'id': 258132198, 'kind': 'aerialway', 'kind_detail': type(None) })
  File "./scripts/../integration-test.py", line 292, in assert_has_feature
    % (properties, closest['properties'], misses)
  File "/opt/circleci/python/2.7.10/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "./scripts/../integration-test.py", line 189, in features_in_tile_layer
    yield features
  File "./scripts/../integration-test.py", line 292, in assert_has_feature
    % (properties, closest['properties'], misses)
Exception: Tile 'http://localhost:38708/roads/16/10910/25120.json': Did not find feature including properties {'kind_detail': <type 'NoneType'>, 'kind': 'aerialway', 'id': 258132198}. The closest match was {u'kind': u'aerialway', u'name': u'Slide Mountain', u'sort_rank': 441, u'kind_detail': u'chair_lift', u'source': u'openstreetmap.org', u'min_zoom': 13.0, u'ref': u'8', u'id': 258132198}: missed {'kind_detail': "'chair_lift' not an instance of <type 'NoneType'>"}.
```

**Comment by nvkelso** [comment]
Noticed during Mapzen docs generator refactoring.

**Comment by nvkelso** [comment]
This was resolved.
