### ISSUE TITLE
be resilient to missing network properties on roads layer

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1242]
* **What did you see?** The vector-datasource schema and functions changed slightly between v1.2 and v1.3. In updating the production database to v1.3 schema (but v1.2 python code) we started seeing errors like the following.
* **What did you expect to see?** No errors ;)

```
Error handling request for /all/17/120891/76253.json: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tileserver/__init__.py", line 222, in __call__    response = self.handle_request(request)
  File "/usr/local/lib/python2.7/dist-packages/tileserver/__init__.py", line 311, in handle_request    cut_coords, self.buffer_cfg)
  File "/usr/local/lib/python2.7/dist-packages/tilequeue/process.py", line 378, in process_coord    feature_layers, nominal_zoom, post_process_data, unpadded_bounds)
  File "/usr/local/lib/python2.7/dist-packages/tilequeue/process.py", line 294, in _process_feature_layers    shape, props, feature_id, nominal_zoom)
  File "/usr/local/lib/python2.7/dist-packages/tilequeue/process.py", line 22, in transform_fn    shape, properties, fid = fn(shape, properties, fid, zoom)
  File "/usr/local/lib/python2.7/dist-packages/vector_datasource-1.2.0-py2.7.egg/vectordatasource/transform.py", line 3969, in extract_network_information    shield_texts.append(_shield_text(network, ref))
  File "/usr/local/lib/python2.7/dist-packages/vector_datasource-1.2.0-py2.7.egg/vectordatasource/transform.py", line 3925, in _shield_text    if network.startswith('ua:'):
  AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by nvkelso** [comment]
Fixed in d44dbf86bec1c5098578d4ca194159bff710f7ed and released in v1.2.1. 

This issue is for porting the fix to v1.3.1.

**Comment by nvkelso** [comment]
@zerebubuth Can you review https://github.com/tilezen/vector-datasource/commit/d44dbf86bec1c5098578d4ca194159bff710f7ed, please? Once verified, apply the change to master and we can cut a new release with this and the islet test change.

**Comment by nvkelso** [comment]
Thanks to @iandees for the quick diagnosis!

**Comment by nvkelso** [comment]
There's another related error coming from this logic that still needs to be cleaned up:

- https://github.com/tilezen/vector-datasource/blob/5625c30c156eb9b11940519ecf4178e982c8fc0d/vectordatasource/transform.py#L3884

```
    if network == 'US:I' or ':national' in network:
        network_code = 1
    elif network == 'US:US' or ':regional' in network:
        network_code = 2
    else:
        network_code = len(network.split(':')) + 3
```

**Comment by iandees** [comment]
There's also

```
2017-05-05_00:10:01.20417 Error handling request for /all/17/112264/51786.json: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tileserver/__init__.py", line 222, in __call__    response = self.handle_request(request)
  File "/usr/local/lib/python2.7/dist-packages/tileserver/__init__.py", line 311, in handle_request    cut_coords, self.buffer_cfg)
  File "/usr/local/lib/python2.7/dist-packages/tilequeue/process.py", line 378, in process_coord    feature_layers, nominal_zoom, post_process_data, unpadded_bounds)
  File "/usr/local/lib/python2.7/dist-packages/tilequeue/process.py", line 294, in _process_feature_layers    shape, props, feature_id, nominal_zoom)
  File "/usr/local/lib/python2.7/dist-packages/tilequeue/process.py", line 22, in transform_fn    shape, properties, fid = fn(shape, properties, fid, zoom)
  File "/usr/local/lib/python2.7/dist-packages/vector_datasource-1.2.0-py2.7.egg/vectordatasource/transform.py", line 3988, in choose_most_important_network    tuples = sorted(zip(networks, shield_texts), key=network_key)
  File "/usr/local/lib/python2.7/dist-packages/vector_datasource-1.2.0-py2.7.egg/vectordatasource/transform.py", line 3986, in network_key    return _network_importance(*t)
  File "/usr/local/lib/python2.7/dist-packages/vector_datasource-1.2.0-py2.7.egg/vectordatasource/transform.py", line 3884, in _network_importance    if network == 'US:I' or ':national' in network:
  TypeError: argument of type 'NoneType' is not iterable
```

and

```
2017-05-04_23:40:47.15487 Error handling request for /all/12/2410/1418.mvt: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tileserver/__init__.py", line 222, in __call__    response = self.handle_request(request)
  File "/usr/local/lib/python2.7/dist-packages/tileserver/__init__.py", line 311, in handle_request    cut_coords, self.buffer_cfg)
  File "/usr/local/lib/python2.7/dist-packages/tilequeue/process.py", line 378, in process_coord    feature_layers, nominal_zoom, post_process_data, unpadded_bounds)
  File "/usr/local/lib/python2.7/dist-packages/tilequeue/process.py", line 294, in _process_feature_layers    shape, props, feature_id, nominal_zoom)
  File "/usr/local/lib/python2.7/dist-packages/tilequeue/process.py", line 22, in transform_fn    shape, properties, fid = fn(shape, properties, fid, zoom)
  File "/usr/local/lib/python2.7/dist-packages/vector_datasource-1.2.0-py2.7.egg/vectordatasource/transform.py", line 3969, in extract_network_information    shield_texts.append(_shield_text(network, ref))
  File "/usr/local/lib/python2.7/dist-packages/vector_datasource-1.2.0-py2.7.egg/vectordatasource/transform.py", line 3932, in _shield_text    if network and network.startswith('GR:') or network.startswith('gr:'):
  AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by nvkelso** [comment]
Let's also add an `integration-test`.

**Comment by nvkelso** [comment]
I think @iandees's second example was already fixed in https://github.com/tilezen/vector-datasource/commit/d44dbf86bec1c5098578d4ca194159bff710f7ed.

**Comment by nvkelso** [comment]
Looks like looks like @zerebubuth already fixed this in https://github.com/tilezen/vector-datasource/commit/8fa73560e0d234cc538191ca9e4cf6e358b0701e#diff-ccacdffc74e3f0be743bf4d7d6a1bb9c for v1.3 series (which we mostly fixed the same way in https://github.com/tilezen/vector-datasource/commit/d44dbf86bec1c5098578d4ca194159bff710f7ed).

**We're only missing one other case from that diff.**

And then he followed up with a unicode edge case in https://github.com/tilezen/vector-datasource/commit/572966cb6847e36a67872bbde264bb179e272094#diff-ccacdffc74e3f0be743bf4d7d6a1bb9c.

I've addressed these in https://github.com/tilezen/vector-datasource/compare/v1.2.1...nvkelso/v1.2.2-gaurd-against-network-none.

Because the changes are already in v1.3 I don't think we need to re-apply them.

**Comment by nvkelso** [comment]
Released in https://github.com/tilezen/vector-datasource/releases/tag/v1.2.2. Already present in v1.3.0
