### ISSUE TITLE
Fix v1.4.0 series test failures (upstream data changes)

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1262]
Circle reports back the following errors (there may be more):

```
[ 172/172] PASS: 'integration-test/993-remove-props-road-merge.py'
FAILED 4 TESTS. For more information, see 'test.log'
[  29/172] FAIL: 'integration-test/291-483-suppress-historical-closed.py'
Traceback (most recent call last):
  File "./scripts/../integration-test.py", line 447, in __call__
    runpy.run_path(f, init_globals=dict(test=self.test_api))
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 240, in run_path
    return _run_module_code(code, init_globals, run_name, path_name)
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "integration-test/291-483-suppress-historical-closed.py", line 12, in <module>
    {'id': 241643507})
  File "./scripts/../integration-test.py", line 354, in assert_no_matching_feature
    "%r" % (properties, layer, feature['properties'])
  File "/opt/circleci/python/2.7.10/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "./scripts/../integration-test.py", line 225, in features_in_tile_layer
    yield features
  File "./scripts/../integration-test.py", line 354, in assert_no_matching_feature
    "%r" % (properties, layer, feature['properties'])
Exception: Tile u'http://localhost:58563/pois/15/5232/12654.json': Found feature matching properties {'id': 241643507} in layer 'pois', but was supposed to find none. For example: {u'kind': u'electronics', u'name': u'Tarrget', u'area': 8984, u'source': u'openstreetmap.org', u'min_zoom': 13.99, u'id': 241643507}


[  62/172] FAIL: 'integration-test/479-barrier-toll_booth.py'
Traceback (most recent call last):
  File "./scripts/../integration-test.py", line 447, in __call__
    runpy.run_path(f, init_globals=dict(test=self.test_api))
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 240, in run_path
    return _run_module_code(code, init_globals, run_name, path_name)
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "integration-test/479-barrier-toll_booth.py", line 4, in <module>
    { 'id': 25814380, 'kind': 'toll_booth' })
  File "./scripts/../integration-test.py", line 304, in assert_has_feature
    % (properties, closest['properties'], misses)
  File "/opt/circleci/python/2.7.10/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "./scripts/../integration-test.py", line 225, in features_in_tile_layer
    yield features
  File "./scripts/../integration-test.py", line 298, in assert_has_feature
    "%r (because layer %r was empty)" % (properties, layer)
Exception: Tile u'http://localhost:58563/pois/16/10471/25323.json': Did not find feature including properties {'kind': 'toll_booth', 'id': 25814380} (because layer 'pois' was empty)


[  75/172] FAIL: 'integration-test/526-inclusive-pois.py'
Traceback (most recent call last):
  File "./scripts/../integration-test.py", line 447, in __call__
    runpy.run_path(f, init_globals=dict(test=self.test_api))
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 240, in run_path
    return _run_module_code(code, init_globals, run_name, path_name)
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "integration-test/526-inclusive-pois.py", line 51, in <module>
    test.assert_has_feature(z, x, y, 'pois', props)
  File "./scripts/../integration-test.py", line 304, in assert_has_feature
    % (properties, closest['properties'], misses)
  File "/opt/circleci/python/2.7.10/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "./scripts/../integration-test.py", line 225, in features_in_tile_layer
    yield features
  File "./scripts/../integration-test.py", line 304, in assert_has_feature
    % (properties, closest['properties'], misses)
Exception: Tile u'http://localhost:58563/pois/16/10480/25332.json': Did not find feature including properties {'kind': 'social_facility', 'for': ['senior', 'disabled']}. The closest match was {u'kind': u'group_home', u'name': u'462 Duboce Apartments', u'for': [u'senior', u'disabled'], u'area': 1283, u'social_facility': u'group_home', u'source': u'openstreetmap.org', u'min_zoom': 17.0, u'id': 121024970}: missed {'kind': "'group_home' != 'social_facility'"}.


[  79/172] FAIL: 'integration-test/546-road-sort-keys-layers.py'
Traceback (most recent call last):
  File "./scripts/../integration-test.py", line 447, in __call__
    runpy.run_path(f, init_globals=dict(test=self.test_api))
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 240, in run_path
    return _run_module_code(code, init_globals, run_name, path_name)
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "integration-test/546-road-sort-keys-layers.py", line 6, in <module>
    "id": 8918870, "sort_rank": 447})
  File "./scripts/../integration-test.py", line 304, in assert_has_feature
    % (properties, closest['properties'], misses)
  File "/opt/circleci/python/2.7.10/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "./scripts/../integration-test.py", line 225, in features_in_tile_layer
    yield features
  File "./scripts/../integration-test.py", line 304, in assert_has_feature
    % (properties, closest['properties'], misses)
Exception: Tile u'http://localhost:58563/roads/16/10483/25340.json': Did not find feature including properties {'sort_rank': 447, 'kind_detail': 'motorway', 'kind': 'highway', 'id': 8918870, 'is_bridge': True}. The closest match was {u'bus_network': None, u'ref': u'I 280', u'bicycle': u'no', u'name': u'Southern Embarcadero Fwy.', u'sort_rank': 446, u'kind_detail': u'motorway', u'oneway': u'yes', u'is_bus_route': True, u'kind': u'highway', u'source': u'openstreetmap.org', u'min_zoom': 8.0, u'bus_shield_text': u'14X', u'is_bridge': True, u'sidewalk': u'none', u'all_bus_shield_texts': [u'14X'], u'all_bus_networks': [None], u'id': 8918870}: missed {'sort_rank': '446 != 447'}.
```

**Comment by nvkelso** [comment]
First error is because Target moved into the old (and `closed`) Best Buy big box.

**Comment by nvkelso** [comment]
Toll both error was because of corrupted OSM data that I've fixed in http://www.openstreetmap.org/changeset/49286563 (see http://www.openstreetmap.org/way/25814380/history).

**Comment by nvkelso** [comment]
**526-inclusive-pois.py** fails because https://www.openstreetmap.org/way/121024970 gained more detail, need to replace with more generic `amenity=social_facility` feature (without `social_facility=*`).

**Comment by nvkelso** [comment]
Lots of roads are changing their `layer=*`, pealing back the onion...
