### ISSUE TITLE
More test failures: 546-road-sort-keys-roads.py (and friends?)

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1285]
Latest CircleCI build failed:

- https://circleci.com/gh/tilezen/vector-datasource/1659

```
[ 172/172] PASS: 'integration-test/993-remove-props-road-merge.py'
FAILED 1 TESTS. For more information, see 'test.log'
[  81/172] FAIL: 'integration-test/546-road-sort-keys-roads.py'
Traceback (most recent call last):
  File "./scripts/../integration-test.py", line 447, in __call__
    runpy.run_path(f, init_globals=dict(test=self.test_api))
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 240, in run_path
    return _run_module_code(code, init_globals, run_name, path_name)
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "integration-test/546-road-sort-keys-roads.py", line 36, in <module>
    "name": "Junipero Serra Blvd.", "is_link": True, "sort_rank": 374})
  File "./scripts/../integration-test.py", line 304, in assert_has_feature
    % (properties, closest['properties'], misses)
  File "/opt/circleci/python/2.7.10/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "./scripts/../integration-test.py", line 225, in features_in_tile_layer
    yield features
  File "./scripts/../integration-test.py", line 304, in assert_has_feature
    % (properties, closest['properties'], misses)
Exception: Tile u'http://localhost:47002/roads/16/10472/25347.json': Did not find feature including properties {'kind': 'highway', 'name': 'Junipero Serra Blvd.', 'sort_rank': 374, 'kind_detail': 'motorway_link', 'is_link': True, 'id': 123456285}. The closest match was {u'kind': u'highway', u'bicycle': u'no', u'name': u'Junipero Serra Blvd.', u'sort_rank': 383, u'kind_detail': u'motorway', u'source': u'openstreetmap.org', u'min_zoom': 8.0, u'ref': u'CA 1', u'id': 123456285}: missed {'sort_rank': '383 != 374', 'kind_detail': "'motorway' != 'motorway_link'", 'is_link': 'None != True'}.


=== Killing test server ===
=== Dropping database "vector_datasource_21622" and cleaning up...
./scripts/setup_and_run_tests.sh: line 50: 23520 Hangup                  python scripts/test_server.py "${dbname}" "${USER}" "${test_server_port}"

./scripts/setup_and_run_tests.sh -j 4 returned exit code 1
```

**Comment by zerebubuth** [comment]
@rmarianski and I were working on that yesterday - looks like we forgot to PR our branch back into master! Ooops. PR is #1286, and fixes the above `motorway_link` issue, as well as a couple of others where dev / prod data had diverged from what's in the fixtures.

**Comment by zerebubuth** [comment]
Tests fixed. [Circle is happy](https://circleci.com/gh/tilezen/vector-datasource/1661?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link), at least for now.
