### ISSUE TITLE
CircleCI reports pip install -Ur requirements.txt fails

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1332]
CircleCI is sad:

https://circleci.com/gh/tilezen/vector-datasource/1774

Previous builds based on the same vector-datasource repo SHA did build correctly, maybe it's a related project listed in requirements.txt? 

```
pip install -Ur requirements.txt
Collecting git+https://github.com/ixc/python-edtf@aad32b8d5cd8848c50fbef92c73697a93cf182ba#edtf (from -r requirements.txt (line 22))
  Cloning https://github.com/ixc/python-edtf (to aad32b8d5cd8848c50fbef92c73697a93cf182ba) to /tmp/pip-OcLnDH-build
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.

  Could not find a tag or branch 'aad32b8d5cd8848c50fbef92c73697a93cf182ba', assuming commit.
Requirement already up-to-date: AppDirs==1.4.3 in /home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages (from -r requirements.txt (line 1))
Requirement already up-to-date: argparse==1.2.1 in /home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages (from -r requirements.txt (line 2))
Requirement already up-to-date: ASTFormatter==0.6.4 in /home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages (from -r requirements.txt (line 3))
Requirement already up-to-date: boto==2.33.0 in /home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages (from -r requirements.txt (line 4))
Requirement already up-to-date: future==0.15.2 in /home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages (from -r requirements.txt (line 5))
Requirement already up-to-date: hiredis==0.2.0 in /home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages (from -r requirements.txt (line 6))
Requirement already up-to-date: lxml==3.6.0 in /home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages (from -r requirements.txt (line 7))
Requirement already up-to-date: ModestMaps==1.4.6 in /home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages (from -r requirements.txt (line 8))
Requirement already up-to-date: protobuf==2.6.0 in /home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages (from -r requirements.txt (line 9))
Requirement already up-to-date: psycopg2==2.5.4 in /home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages (from -r requirements.txt (line 10))
Requirement already up-to-date: pyclipper==1.0.5 in /home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages (from -r requirements.txt (line 11))
Requirement already up-to-date: pycountry==1.20 in /home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages (from -r requirements.txt (line 12))
Requirement already up-to-date: python-dateutil==2.4.2 in /home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages (from -r requirements.txt (line 13))
Requirement already up-to-date: PyYAML==3.11 in /home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages (from -r requirements.txt (line 14))
Requirement already up-to-date: redis==2.10.5 in /home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages (from -r requirements.txt (line 15))
Requirement already up-to-date: Shapely==1.4.3 in /home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages (from -r requirements.txt (line 16))
Requirement already up-to-date: simplejson==3.6.4 in /home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages (from -r requirements.txt (line 17))
Requirement already up-to-date: six==1.10.0 in /home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages (from -r requirements.txt (line 18))
Requirement already up-to-date: StreetNames==0.1.5 in /home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages (from -r requirements.txt (line 19))
Requirement already up-to-date: Werkzeug==0.9.6 in /home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages (from -r requirements.txt (line 20))
Requirement already up-to-date: wsgiref==0.1.2 in /opt/circleci/python/2.7.10/lib/python2.7 (from -r requirements.txt (line 21))
Collecting mapbox-vector-tile from git+https://github.com/tilezen/mapbox-vector-tile@master#egg=mapbox-vector-tile (from -r requirements.txt (line 23))
  Cloning https://github.com/tilezen/mapbox-vector-tile (to master) to /tmp/pip-build-qAoXjN/mapbox-vector-tile
Collecting tilequeue from git+https://github.com/tilezen/tilequeue@master#egg=tilequeue (from -r requirements.txt (line 24))
  Cloning https://github.com/tilezen/tilequeue (to master) to /tmp/pip-build-qAoXjN/tilequeue
Collecting tileserver from git+https://github.com/tilezen/tileserver@master#egg=tileserver (from -r requirements.txt (line 25))
  Cloning https://github.com/tilezen/tileserver (to master) to /tmp/pip-build-qAoXjN/tileserver
Collecting setuptools (from protobuf==2.6.0->-r requirements.txt (line 9))
  Downloading setuptools-36.2.2-py2.py3-none-any.whl (477kB)
    100% |████████████████████████████████| 481kB 1.9MB/s 
Requirement already up-to-date: Jinja2 in /home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages (from tilequeue->-r requirements.txt (line 24))
Requirement already up-to-date: pyproj in /home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages (from tilequeue->-r requirements.txt (line 24))
Requirement already up-to-date: requests in /home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages (from tilequeue->-r requirements.txt (line 24))
Requirement already up-to-date: statsd in /home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages (from tilequeue->-r requirements.txt (line 24))
Requirement already up-to-date: ujson in /home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages (from tilequeue->-r requirements.txt (line 24))
Requirement already up-to-date: zope.dottedname in /home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages (from tilequeue->-r requirements.txt (line 24))
Requirement already up-to-date: MarkupSafe>=0.23 in /home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages (from Jinja2->tilequeue->-r requirements.txt (line 24))
Requirement already up-to-date: urllib3<1.22,>=1.21.1 in /home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages (from requests->tilequeue->-r requirements.txt (line 24))
Requirement already up-to-date: idna<2.6,>=2.5 in /home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages (from requests->tilequeue->-r requirements.txt (line 24))
Requirement already up-to-date: certifi>=2017.4.17 in /home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages (from requests->tilequeue->-r requirements.txt (line 24))
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in /home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages (from requests->tilequeue->-r requirements.txt (line 24))
Installing collected packages: setuptools, mapbox-vector-tile, edtf, tilequeue, tileserver
  Found existing installation: setuptools 36.2.0
    Uninstalling setuptools-36.2.0:
      Successfully uninstalled setuptools-36.2.0
  Rolling back uninstall of setuptools
Exception:
Traceback (most recent call last):
  File "/home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages/pip/wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "/home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages/pip/locations.py", line 140, in distutils_scheme
    d = Distribution(dist_args)
  File "/home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages/setuptools/dist.py", line 365, in __init__
    self._finalize_requires()
  File "/home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages/setuptools/dist.py", line 372, in _finalize_requires
    if not self.install_requires:
AttributeError: Distribution instance has no attribute 'install_requires'

pip install -Ur requirements.txt returned exit code 2

Action failed: pip install -Ur requirements.txt
```

**Comment by nvkelso** [comment]
And "burp", build https://circleci.com/gh/tilezen/vector-datasource/1775 is fine. (Built without cache.)
