### ISSUE TITLE
tests 1252 is now failing

### ISSUE THREAD

**Issue by matkoniecz** [tilezen/vector-datasource#1344]
* **What did you see?**

test 1252 is now failing (and was always failing)

```

[  23/175] FAIL: 'integration-test/1252-roads-surface.py'
Traceback (most recent call last):
  File "./scripts/../integration-test.py", line 448, in __call__
    runpy.run_path(f, init_globals=dict(test=self.test_api))
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 240, in run_path
    return _run_module_code(code, init_globals, run_name, path_name)
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "integration-test/1252-roads-surface.py", line 40, in <module>
    { 'id': 58691615, 'kind_detail': 'track', 'surface': 'concrete_lanes'})
  File "./scripts/../integration-test.py", line 305, in assert_has_feature
    % (properties, closest['properties'], misses)
  File "/opt/circleci/python/2.7.10/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "./scripts/../integration-test.py", line 226, in features_in_tile_layer
    yield features
  File "./scripts/../integration-test.py", line 299, in assert_has_feature
    "%r (because layer %r was empty)" % (properties, layer)
Exception: Tile u'http://localhost:44395/roads/11/1091/673.json': Did not find feature including properties {'kind_detail': 'track', 'id': 58691615, 'surface': 'concrete_lanes'} (because layer 'roads' was empty)

```

* **What did you expect to see?**

test 1252 is not failing

----

#1334  added new tests.

I  created PR to run tests independently from my local instance - as I was confused by failing test. Even after reload of testing database test failed with claim that tile 11/1091/673 has no road layer. As the tile at http://tile.mapzen.com/mapzen/vector/v1/roads/11/1091/673.json has road layer I thought that it is some kind of local bug.

I was still testing some things (value filtering by whitelist and trying tests to pass locally) at time that PR was merged (BTW, PR was merged as it was still marked as [wip] by me)

Due to #1339 it was missed that tests on CircleCi are still failing for the same reason as locally (I was happy that tests are passing and thought that everything is OK and was trying to investigate what went wrong locally and noticed problem only as I compared local testing log to CircleCi testing log, what happened after PR was merged).

I opened this issue as it turned from unfinished PR to issue present in master.

**Comment by matkoniecz** [comment]
For start: http://tile.mapzen.com/mapzen/vector/v1/roads/11/1091/673.json?api_key=YOURMAPZENKEY - road layer is not empty

So either I am highly confused by something, or somehow one of recent PRs dropped highway=track from z11 or test script fails to setup database correctly or something else is broken.
