### ISSUE TITLE
No output calc rule error during dev build

### ISSUE THREAD

**Issue by rmarianski** [tilezen/vector-datasource#1375]
```
2017-08-17_21:02:59.66974 process - ERROR - Error processing: 6/35/23 - Traceback (most recent call last): |   File "/usr/local/lib/python2.7/dist-packages/tilequeue/worker.py", line 280, in __call__    cut_coords, self.buffer_cfg, self.output_calc_mapping) |   File "/usr/local/lib/python2.7/dist-packages/tilequeue/process.py", line 453, in process_coord    output_calc_spec) |   File "/usr/local/lib/python2.7/dist-packages/tilequeue/process.py", line 331, in process_coord_no_format    assert output_props, 'No output calc rule matched' | AssertionError: No output calc rule matched
```

**Comment by rmarianski** [comment]
This ends up getting fixed by https://github.com/tilezen/vector-datasource/pull/1378 too.

The coordinates with the errors were 5/17/11, 6/35/23, 7/70/46.
