### ISSUE TITLE
Testing failure on master

### ISSUE THREAD

**Issue by pnorman** [tilezen/vector-datasource#1470]
Running `python integration-test/__init__.py --regenerate` has the following failures

```
======================================================================                                                                                            [147/1845]
FAIL: test_bicycle_junction (integration-test.592-add-adjust-bicycle-pois.AddAdjustBicyclePois)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pnorman/osm/tilezen/vector-datasource/integration-test/592-add-adjust-bicycle-pois.py", line 75, in test_bicycle_junction
    'bicycle_network': 'lcn'})
  File "/home/pnorman/osm/tilezen/vector-datasource/integration-test/__init__.py", line 1399, in assert_has_feature                                                             self.test_instance.assert_has_feature(z, x, y, layer, props)
  File "integration-test/__init__.py", line 1258, in assert_has_feature
    self.assertions.assert_has_feature(z, x, y, layer, props)
  File "integration-test/__init__.py", line 1109, in assert_has_feature
    (properties, closest['properties'], misses))
AssertionError: Did not find feature including properties {'kind': 'bicycle_junction', 'ref': '1', 'min_zoom': 16, 'bicycle_network': 'lcn'}. The closest match was {'source
': 'openstreetmap.org', 'kind': 'information', 'min_zoom': 16.0, 'id': 3269815503}: missed {'kind': "'information' != 'bicycle_junction'", 'ref': "None != '1'", 'bicycle_ne
twork': "None != 'lcn'"}.

======================================================================
FAIL: test_named_forest (integration-test.1103-no-natural-pois.NoNaturalPois)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pnorman/osm/tilezen/vector-datasource/integration-test/1103-no-natural-pois.py", line 49, in test_named_forest
    'label_placement': True})
  File "/home/pnorman/osm/tilezen/vector-datasource/integration-test/__init__.py", line 1399, in assert_has_feature
    self.test_instance.assert_has_feature(z, x, y, layer, props)
  File "integration-test/__init__.py", line 1258, in assert_has_feature
    self.assertions.assert_has_feature(z, x, y, layer, props)
  File "integration-test/__init__.py", line 1109, in assert_has_feature
    (properties, closest['properties'], misses))
AssertionError: Did not find feature including properties {'label_placement': True, 'kind': 'natural_forest', 'id': 316516905}. The closest match was {'kind': 'forest', 'ar
ea': 3597, 'sort_rank': 31, 'source': 'openstreetmap.org', 'min_zoom': 15.0, 'tier': 2, 'id': 316516905}: missed {'label_placement': 'None != True', 'kind': "'forest' != 'n
atural_forest'"}.

======================================================================
FAIL: test_sfo (integration-test.398-airport-iata-codes.AirportIataCodes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pnorman/osm/tilezen/vector-datasource/integration-test/398-airport-iata-codes.py", line 11, in test_sfo
    {'kind': 'aerodrome', 'iata': 'SFO'})
  File "/home/pnorman/osm/tilezen/vector-datasource/integration-test/__init__.py", line 1399, in assert_has_feature
    self.test_instance.assert_has_feature(z, x, y, layer, props)
  File "integration-test/__init__.py", line 1258, in assert_has_feature
    self.assertions.assert_has_feature(z, x, y, layer, props)
  File "integration-test/__init__.py", line 1102, in assert_has_feature
    "layer %r was empty)" % (properties, layer))
AssertionError: Did not find feature including properties {'kind': 'aerodrome', 'iata': 'SFO'} (because layer 'pois' was empty)

======================================================================                                                                                            [101/1845]
FAIL: test_broadway_pier (integration-test.1178-earlier-piers.EarlierPiers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pnorman/osm/tilezen/vector-datasource/integration-test/1178-earlier-piers.py", line 29, in test_broadway_pier
    {'id': 275609725, 'kind': 'pier', 'min_zoom': 12})
  File "/home/pnorman/osm/tilezen/vector-datasource/integration-test/__init__.py", line 1399, in assert_has_feature
    self.test_instance.assert_has_feature(z, x, y, layer, props)
  File "integration-test/__init__.py", line 1258, in assert_has_feature
    self.assertions.assert_has_feature(z, x, y, layer, props)
  File "integration-test/__init__.py", line 1109, in assert_has_feature
    (properties, closest['properties'], misses))
AssertionError: Did not find feature including properties {'kind': 'pier', 'min_zoom': 12, 'id': 275609725}. The closest match was {'source': 'openstreetmap.org', 'kind': '
pier', 'name': 'Broadway Pier', 'area': 17763, 'sort_rank': 228, 'min_zoom': 12.01, 'id': 275609725}: missed {'min_zoom': '12.01 != 12'}.

======================================================================
FAIL: test_railway_halt (integration-test.1218-poni-whitelist.PoniWhitelist)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pnorman/osm/tilezen/vector-datasource/integration-test/1218-poni-whitelist.py", line 309, in test_railway_halt
    {'id': 2382580308})
  File "/home/pnorman/osm/tilezen/vector-datasource/integration-test/__init__.py", line 1399, in assert_has_feature
    self.test_instance.assert_has_feature(z, x, y, layer, props)
  File "integration-test/__init__.py", line 1258, in assert_has_feature
    self.assertions.assert_has_feature(z, x, y, layer, props)
  File "integration-test/__init__.py", line 1102, in assert_has_feature
    "layer %r was empty)" % (properties, layer))
AssertionError: Did not find feature including properties {'id': 2382580308} (because layer 'pois' was empty)

======================================================================
FAIL: test_museum (integration-test.580-kind-csv.KindCsv)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pnorman/osm/tilezen/vector-datasource/integration-test/580-kind-csv.py", line 17, in test_museum
    {'kind': 'museum'})
  File "/home/pnorman/osm/tilezen/vector-datasource/integration-test/__init__.py", line 1399, in assert_has_feature
    self.test_instance.assert_has_feature(z, x, y, layer, props)
  File "integration-test/__init__.py", line 1258, in assert_has_feature
    self.assertions.assert_has_feature(z, x, y, layer, props)
  File "integration-test/__init__.py", line 1102, in assert_has_feature
    "layer %r was empty)" % (properties, layer))
AssertionError: Did not find feature including properties {'kind': 'museum'} (because layer 'pois' was empty)

======================================================================                                                                                             [58/1845]
FAIL: test_198th_street (integration-test.647-cycle-route.CycleRoute)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pnorman/osm/tilezen/vector-datasource/integration-test/647-cycle-route.py", line 51, in test_198th_street
    'cycleway': 'shared_lane'})
  File "/home/pnorman/osm/tilezen/vector-datasource/integration-test/__init__.py", line 1399, in assert_has_feature
    self.test_instance.assert_has_feature(z, x, y, layer, props)
  File "integration-test/__init__.py", line 1258, in assert_has_feature
    self.assertions.assert_has_feature(z, x, y, layer, props)
  File "integration-test/__init__.py", line 1109, in assert_has_feature
    (properties, closest['properties'], misses))
AssertionError: Did not find feature including properties {'kind': 'major_road', 'cycleway': 'shared_lane', 'id': 138388021, 'bicycle_network': 'icn'}. The closest match wa
s {'kind': 'major_road', 'name': '198th St.', 'sort_rank': 377, 'kind_detail': 'tertiary', 'is_bicycle_related': True, 'cycleway': 'shared_lane', 'source': 'openstreetmap.o
rg', 'min_zoom': 11.0, 'bicycle_network': 'lcn', 'id': 138388021}: missed {'bicycle_network': "'lcn' != 'icn'"}.

======================================================================
FAIL: test_trunk_level_0 (integration-test.546-road-sort-keys-tunnel.RoadSortKeysTunnel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pnorman/osm/tilezen/vector-datasource/integration-test/546-road-sort-keys-tunnel.py", line 20, in test_trunk_level_0
    "name": "McCarter Hwy.", "is_tunnel": True, "sort_rank": 331})
  File "/home/pnorman/osm/tilezen/vector-datasource/integration-test/__init__.py", line 1399, in assert_has_feature
    self.test_instance.assert_has_feature(z, x, y, layer, props)
  File "integration-test/__init__.py", line 1258, in assert_has_feature
    self.assertions.assert_has_feature(z, x, y, layer, props)
  File "integration-test/__init__.py", line 1102, in assert_has_feature
    "layer %r was empty)" % (properties, layer))
AssertionError: Did not find feature including properties {'kind': 'major_road', 'name': 'McCarter Hwy.', 'sort_rank': 331, 'kind_detail': 'trunk', 'is_tunnel': True, 'id':
 259492789} (because layer 'roads' was empty)

======================================================================                                                                                             [27/1845]
FAIL: test_first_capitol_dr_i70_business (integration-test.1387-business-and-spur-routes.BusinessAndSpurRoutes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pnorman/osm/tilezen/vector-datasource/integration-test/1387-business-and-spur-routes.py", line 22, in test_first_capitol_dr_i70_business
    1933234, 12276055, '16/16294/25097', '70', 'US:I:Business')
  File "/home/pnorman/osm/tilezen/vector-datasource/integration-test/1387-business-and-spur-routes.py", line 18, in _check_route_relation
    {'id': way_id, 'shield_text': shield_text, 'network': network})
  File "/home/pnorman/osm/tilezen/vector-datasource/integration-test/__init__.py", line 1399, in assert_has_feature
    self.test_instance.assert_has_feature(z, x, y, layer, props)
  File "integration-test/__init__.py", line 1258, in assert_has_feature
    self.assertions.assert_has_feature(z, x, y, layer, props)
  File "integration-test/__init__.py", line 1109, in assert_has_feature
    (properties, closest['properties'], misses))
AssertionError: Did not find feature including properties {'shield_text': '70', 'id': 12276055, 'network': 'US:I:Business'}. The closest match was {'kind': 'major_road', 'n
ame': 'First Capitol Dr.', 'sort_rank': 380, 'kind_detail': 'primary', 'source': 'openstreetmap.org', 'min_zoom': 8.0, 'all_networks': ['US:I'], 'shield_text': u'70', 'ref'
: 'I 70 Business;MO 94', 'id': 12276055, 'all_shield_texts': [u'70'], 'network': 'US:I'}: missed {'network': "'US:I' != 'US:I:Business'"}.

======================================================================
FAIL: test_nj_cr (integration-test.1387-business-and-spur-routes.BusinessAndSpurRoutes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pnorman/osm/tilezen/vector-datasource/integration-test/1387-business-and-spur-routes.py", line 34, in test_nj_cr
    941526, 60523740, '16/19192/24767', '526', 'US:NJ:CR:Spur')
  File "/home/pnorman/osm/tilezen/vector-datasource/integration-test/1387-business-and-spur-routes.py", line 18, in _check_route_relation
    {'id': way_id, 'shield_text': shield_text, 'network': network})
  File "/home/pnorman/osm/tilezen/vector-datasource/integration-test/__init__.py", line 1399, in assert_has_feature
    self.test_instance.assert_has_feature(z, x, y, layer, props)
  File "integration-test/__init__.py", line 1258, in assert_has_feature
    self.assertions.assert_has_feature(z, x, y, layer, props)
  File "integration-test/__init__.py", line 1109, in assert_has_feature
    (properties, closest['properties'], misses))
AssertionError: Did not find feature including properties {'shield_text': '526', 'id': 60523740, 'network': 'US:NJ:CR:Spur'}. The closest match was {'kind': 'major_road', '
name': 'County Road 526 Spur', 'sort_rank': 380, 'kind_detail': 'primary', 'source': 'openstreetmap.org', 'min_zoom': 8.0, 'all_networks': ['US:NJ:CR'], 'shield_text': u'52
6', 'ref': 'CR 526-S', 'id': 60523740, 'all_shield_texts': [u'526'], 'network': 'US:NJ:CR'}: missed {'network': "'US:NJ:CR' != 'US:NJ:CR:Spur'"}.

======================================================================
FAIL: test_nj_essex (integration-test.1387-business-and-spur-routes.BusinessAndSpurRoutes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pnorman/osm/tilezen/vector-datasource/integration-test/1387-business-and-spur-routes.py", line 30, in test_nj_essex
    945855, 221295008, '16/19267/24623', '672', 'US:NJ:Essex:Spur')
  File "/home/pnorman/osm/tilezen/vector-datasource/integration-test/1387-business-and-spur-routes.py", line 18, in _check_route_relation
    {'id': way_id, 'shield_text': shield_text, 'network': network})
  File "/home/pnorman/osm/tilezen/vector-datasource/integration-test/__init__.py", line 1399, in assert_has_feature
    self.test_instance.assert_has_feature(z, x, y, layer, props)
  File "integration-test/__init__.py", line 1258, in assert_has_feature
    self.assertions.assert_has_feature(z, x, y, layer, props)
  File "integration-test/__init__.py", line 1109, in assert_has_feature
    (properties, closest['properties'], misses))
AssertionError: Did not find feature including properties {'shield_text': '672', 'id': 221295008, 'network': 'US:NJ:Essex:Spur'}. The closest match was {'kind': 'major_road
', 'name': 'Bridge St.', 'sort_rank': 377, 'kind_detail': 'tertiary', 'source': 'openstreetmap.org', 'min_zoom': 11.0, 'all_networks': ['US:NJ:Essex'], 'shield_text': u'672
', 'ref': '(672 Spur)', 'id': 221295008, 'all_shield_texts': [u'672'], 'network': 'US:NJ:Essex'}: missed {'network': "'US:NJ:Essex' != 'US:NJ:Essex:Spur'"}.

======================================================================
FAIL: test_park_protect_class_5 (integration-test.987-national-forests.NationalForests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pnorman/osm/tilezen/vector-datasource/integration-test/987-national-forests.py", line 191, in test_park_protect_class_5
    {'kind': 'park', 'id': -318202})
  File "/home/pnorman/osm/tilezen/vector-datasource/integration-test/__init__.py", line 1399, in assert_has_feature
    self.test_instance.assert_has_feature(z, x, y, layer, props)
  File "integration-test/__init__.py", line 1258, in assert_has_feature
    self.assertions.assert_has_feature(z, x, y, layer, props)
  File "integration-test/__init__.py", line 1109, in assert_has_feature
    (properties, closest['properties'], misses))
AssertionError: Did not find feature including properties {'kind': 'park', 'id': -318202}. The closest match was {'kind': 'national_park', 'protect_class': '5', 'area': 239
31368, 'sort_rank': 18, 'source': 'openstreetmap.org', 'min_zoom': 8.0, 'tier': 1, 'id': -318202, 'osm_relation': True}: missed {'kind': "'national_park' != 'park'"}.

----------------------------------------------------------------------
```

**Comment by nvkelso** [comment]
Closed for inactivity.
