### ISSUE TITLE
GeometryCollection in tile data

### ISSUE THREAD

**Issue by zerebubuth** [tilezen/vector-datasource#1505]
* **What did you see?**

```
Traceback (most recent call last): 
 File "/usr/src/tilequeue/tilequeue/command.py", line 2173, in tilequeue_meta_tile output_calc_mapping 
 File "/usr/src/tilequeue/tilequeue/process.py", line 500, in process_coord unpadded_bounds, cut_coords, buffer_cfg, extra_data, scale) 
 File "/usr/src/tilequeue/tilequeue/process.py", line 467, in format_coord _calculate_scale(scale, cut_coord, nominal_zoom), buffer_cfg) 
 File "/usr/src/tilequeue/tilequeue/process.py", line 437, in _cut_child_tiles unpadded_cut_bounds, scale, buffer_cfg) 
 File "/usr/src/tilequeue/tilequeue/process.py", line 420, in _format_feature_layers meters_per_pixel_dim, buffer_cfg) 
 File "/usr/src/tilequeue/tilequeue/process.py", line 192, in _create_formatted_tile unpadded_bounds, unpadded_bounds_lnglat, scale) 
 File "/usr/src/tilequeue/tilequeue/format/__init__.py", line 35, in format_tile bounds_lnglat, extents) 
 File "/usr/src/tilequeue/tilequeue/format/__init__.py", line 81, in format_mvt mvt_encode(fp, mvt_layers, bounds_merc, extents) 
 File "/usr/src/tilequeue/tilequeue/format/mvt.py", line 11, in encode extents=extents, 
 File "/usr/local/lib/python2.7/site-packages/mapbox_vector_tile/__init__.py", line 26, in encode quantize_bounds, y_coord_down) 
 File "/usr/local/lib/python2.7/site-packages/mapbox_vector_tile/encoder.py", line 92, in addFeatures self.addFeature(feature, shape, y_coord_down) 
 File "/usr/local/lib/python2.7/site-packages/mapbox_vector_tile/encoder.py", line 220, in addFeature feature_type = self._get_feature_type(shape) 
 File "/usr/local/lib/python2.7/site-packages/mapbox_vector_tile/encoder.py", line 247, in _get_feature_type raise ValueError('Encoding geometry collections not supported') 
 ValueError: Encoding geometry collections not supported
```

* **What did you expect to see?**

:heavy_check_mark: :tada: :fireworks: 

* **What map location are you having problems with?**

* `10/896/368`, which is on the far east coast of Russia.
* `10/609/382`, which is near the north coast of Turkey.

(I'm pretty sure the location has nothing to do with it - there's just some geometry operation happening there by chance which isn't happening elsewhere.)

The traceback points to [`mapbox_vector_tile`](https://github.com/tilezen/mapbox-vector-tile/blob/46629e478935954fc2dcbd8d17d005546b8d31a0/mapbox_vector_tile/encoder.py#L247), but the actual error occurred earlier, when the process performed a geometry operation resulting in a GeometryCollection result and _didn't check it_. This is usually a clipping or intersecting operation, but doesn't always have to be. The majority of the geometry operations are performed in `transform.py` here, so this is where I've started the issue. But it's also possible that the problem is in [`tilequeue`](https://github.com/tilezen/tilequeue) instead.

As @rmarianski has said somewhere (but I couldn't find, sorry, or I'd have linked), we might want to wrap all geometry operations so that we're required to explicitly pass in the kinds of geometry we expect in return. This would help keep us from creating new code with the possibility for these errors.

**Comment by nvkelso** [comment]
We've moved to different MVT encoder, closing.
