### ISSUE TITLE
Be more robust to None in road network code.

### ISSUE THREAD

**Issue by zerebubuth** [tilezen/vector-datasource#1555]
Backtrace:

```
Traceback (most recent call last): 
   File "/usr/src/tilequeue/tilequeue/command.py", line 2287, in tilequeue_meta_tile_low_zoom    formatted_tiles, _ = processor.process_tiles() 
   File "/usr/src/tilequeue/tilequeue/process.py", line 757, in process_tiles    cut_coords, self.buffer_cfg, self.output_calc_mapping 
   File "/usr/src/tilequeue/tilequeue/process.py", line 498, in process_coord    output_calc_spec) 
   File "/usr/src/tilequeue/tilequeue/process.py", line 398, in process_coord_no_format    unpadded_bounds) 
   File "/usr/src/tilequeue/tilequeue/process.py", line 84, in _postprocess_data    layer = fn(ctx) 
   File "/usr/src/vector-datasource/vectordatasource/transform.py", line 7235, in road_networks    shape, props, fid = fn(shape, props, fid, zoom) 
   File "/usr/src/vector-datasource/vectordatasource/transform.py", line 7203, in _fixup_country_specific_networks    network, ref = logic.fix(network, ref) 
   File "/usr/src/vector-datasource/vectordatasource/transform.py", line 5977, in _normalize_pl_netref    if ref.startswith('A'): 
 AttributeError: 'NoneType' object has no attribute 'startswith'
```

This results from assuming that `ref` is a `str` without checking. In all of this code, either `ref` or `network` could be `None`. Therefore, we need to check that it's not `None` first (ideally `isinstance`, but practically if it's truthy it's going to be a string).

**Comment by nvkelso** [comment]
@zerebubuth Is this issue good to close? Is there a good place on the map to look for verification?

**Comment by zerebubuth** [comment]
Yes, I think so. We were missing a lot of tiles, including `3/4/2` and `3/5/1`, both of which seem to be OK in the current build:

<img width="1680" alt="screen shot 2018-09-05 at 09 43 52" src="https://user-images.githubusercontent.com/271360/45082067-736d9080-b0f0-11e8-90b6-d7346ca1ea63.png">
