### ISSUE TITLE
two new water failures

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#2038]
two new failures:
```
======================================================================
FAIL: test_drop_label (integration-test.1477-water-layer-too-big.WaterLayerTooBigTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/circleci/project/integration-test/1477-water-layer-too-big.py", line 46, in test_drop_label
    'name': 'Foo',
  File "/home/circleci/project/integration-test/__init__.py", line 1492, in assert_has_feature
    self.test_instance.assert_has_feature(z, x, y, layer, props)
  File "integration-test/__init__.py", line 1325, in assert_has_feature
    self.assertions.assert_has_feature(z, x, y, layer, props)
  File "integration-test/__init__.py", line 1161, in assert_has_feature
    (properties, closest['properties'], misses))
AssertionError: Did not find feature including properties {'kind': 'water', 'name': 'Foo'}. The closest match was {'sort_rank': 367, 'kind': 'water'}: missed {'name': "None != 'Foo'"}.

======================================================================

======================================================================
FAIL: test_bays (integration-test.1838-too-many-bays.BayTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/circleci/project/integration-test/1838-too-many-bays.py", line 37, in test_bays
    self.assertEqual(2, len(features))
AssertionError: 2 != 10

======================================================================
```

_Originally posted by @peitili in https://github.com/tilezen/vector-datasource/issues/2010#issuecomment-996266414_

**Comment by nvkelso** [comment]
See 0e791383fc8b4f6e2e1339acd8925057b4353798.
