### ISSUE TITLE
"ProgrammingError: column mz_water_min_zoom does not exist" when zooming out of map

### ISSUE THREAD

**Issue by mr** [tilezen/vector-datasource#741]
If I zoom out too far on the map, these errors show up in my tileserver output. The error causes some tiles to not be created.

```
127.0.0.1 - - [22/Apr/2016 11:13:15] "GET /all/8/72/95.mvt HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/mattro/workspace/tileserver/tileserver/__init__.py", line 190, in __call__
    response = self.handle_request(request)
  File "/Users/mattro/workspace/tileserver/tileserver/__init__.py", line 277, in handle_request
    feature_data_all = self.data_fetcher(coord, self.layer_config.all_layers)
  File "/Users/mattro/workspace/tileserver/env/lib/python2.7/site-packages/tilequeue/query.py", line 195, in __call__
    raise async_exception
ProgrammingError: column "mz_water_min_zoom" does not exist
LINE 66:   mz_water_min_zoom <= 8 AND
```

**Comment by nvkelso** [comment]
This problem exits on master, but should be ok on the last tagged release. We're in the middle of a refactor, this edge case should be resolved today. Thanks for flagging it!

**Comment by nvkelso** [comment]
Hi @mr, has this problem been resolved for you?

**Comment by nvkelso** [comment]
Closing for inactivity.
